obj-m += ttyM.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
test:
	sudo dmesg -C
	sudo insmod ttyM.ko
	sudo rmmod ttyM.ko
	sudo dmesg
